## Kubernetes specific settings
#
#  DO NOT PROMOTE
#
#  This is Environment Specific.
#  - Replicas
#  - Resource Limit
#  - Health Check
#  - Affinity
#  - Persistent Volume

replicas: 1
resources:
  limits:
    cpu: 2
    memory: 1280Mi
  requests:
    cpu: 1
    memory: 640Mi
ingress:
  enabled: true
  host: demo-java.papermint.io
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"