apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.appname }}
    release: {{ .Release.Name }}
  name: {{ .Values.appname }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appname }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      containers:
        - name: main
          image: "{{.Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"

          {{- if .Values.ports }}
          ports:
            {{- range .Values.ports }}
            - containerPort: {{ . }}
            {{- end }}
          {{- end }}

          {{- if or .Values.env .Values.global.env }}
          env:
            {{- if .Values.env }}
            {{- range $name, $value := .Values.env }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            {{- if .Values.global.env }}
            {{- range $name, $value := .Values.global.env }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          {{- end }}

          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

        {{- if .Values.volumes }}
        volumeMounts:
          {{- range .Values.volumes }}
          - name: {{ .name }}
            mountPath: {{ .mountPath }}
          {{- end }}
        {{- end }}

      {{- if .Values.volumes }}
      volumes:
        {{- range .Values.volumes }}
        - name: {{ .name }}
          {{- if .persistence.enabled }}
          persistenceVolumeClaim:
            claimName: {{ .name }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }}
      {{- end }}