apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL3Rjci50a3MudHJ1ZWlkYy5jb20iOnsidXNlcm5hbWUiOiJyb2JvdCRjbHVzdGVyMCIsInBhc3N3b3JkIjoiYTBncUdjWVIwZFA0eGhaRGd0cXZZMHNIaTZzajg1Vk0iLCJhdXRoIjoiY205aWIzUWtZMngxYzNSbGNqQTZZVEJuY1VkaldWSXdaRkEwZUdoYVJHZDBjWFpaTUhOSWFUWnphamcxVmswPSJ9fX0=
kind: Secret
metadata:
  name: sandbox-regcred
type: kubernetes.io/dockerconfigjson